//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> VenueTypeId { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual VenueType VenueType { get; set; }
    }
}
